swagger: "2.0"

info:
  title: "Demo Calculation Hub"
  version: "1.0"

basePath: /app

paths:
  /mean/{array}:
    post:
      summary: 发送请求
      description: 发送请求
      operationId: app.post_mean
      produces:
      - text/plain;
      responses:
        200:
          description: mean response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number



  