swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /solarcalsupp

host: {{host}}

paths:
  /calpoint:
    post:
      summary: 计算得分
      description: 得分落在(-1,1)区间。value 为实际值 ，expect 是期望值， direction 是方向，也可用于权值，负数为越小越好，正数为越大越好.输入可以是序列。
      operationId: solarcalsupp.post_calpoint
      produces:
      - text/plain;
      responses:
        200:
          description: calpoint response
          schema:
            type: number
          examples:
            "text/plain": "0.02123"
      parameters:
      - name: value
        in: query
        description: 实际值
        required: true
        type: array
        items:
          type: number
      - name: expect
        in: query
        description: 期望值
        required: true
        type: array
        items:
          type: number
      - name: direction
        in: query
        description: 权值向量。绝对值和为1。 -0.3, -0.2, -0.2, -0.3
        required: true
        type: array
        items:
          type: number

  /generatelinear:
    post:
      summary: 生成拟合曲线图
      description: 计算最优多项式拟合，生成曲线图
      operationId: solarcalsupp.post_generatelinear
      produces:
      - text/plain;
      responses:
        200:
          description: 生成后返回文件名。
          schema:
            type: string
          examples:
            "text/plain": "6080carlinear.png"
      parameters:
      - name: array
        in: query
        description: array to calulate.
        required: true
        type: array
        items:
          type: number
      - name: batch
        in: query
        description: 批次号
        type: string
      - name: index
        in: query
        description: 指标名称
        type: string
      - name: dpi
        in: query
        description: 图片象素
        type: number

  /generategraph:
    post:
      summary: 生成离散曲线图
      description: 通过数据生成离散折线图
      operationId: solarcalsupp.post_generategraph
      produces:
      - text/plain;
      responses:
        200:
          description: 生成后返回文件名。
          schema:
            type: string
          examples:
            "text/plain": "5550multiplot.png"
      parameters:
      - name: array
        in: query
        description: array to calulate.
        required: true
        type: array
        items:
          type: number
      - name: batch
        in: query
        description: 批次号
        type: string
      - name: index
        in: query
        description: 指标名称
        type: string
      - name: dpi
        in: query
        description: 图片象素
        type: number

  /kmeantrain:
    post:
      summary: 训练分类模型
      description: 通过数据生成KMEAN分类中心值
      operationId: solarcalsupp.post_kmeantrain
      produces:
      - text/plain;
      responses:
        200:
          description: 返回中心值。
          schema:
            type: string
          examples:
            "text/plain": '{"a":{"DFA":0.9685352278,"violmax":5.7472284538,"maxpeaksqt":2.1221870644},"b":{"DFA":1.1660155328,"violmax":14.9333333858,"maxpeaksqt":10.5380230189},"c":{"DFA":1.3348613923,"violmax":31.4501159539,"maxpeaksqt":28.2966994282},"d":{"DFA":1.976394192,"violmax":250.3326660686,"maxpeaksqt":4.9052745478}}'
      parameters:
      - name: array
        in: query
        description: array to calulate. '[{"SR_POSITION.post_std":"0.0015988026828093313","CASTER_LINESPEED.post_maxsqt":"0.004896569043872487","CASTER_POOL_LEVEL.post_rollingvarmax":"4.107023411384234e-06","MILLINLETTEMP.post_maxpeaksqt":"0","CASTER_POOL_LEVEL.post_logVolatility":"0.003801594278138662","MILLINLETTEMP.post_dfa":"0.7239542305546263"}]'
        required: true
        type: string
      - name: featurename
        in: query
        required: true
        description: 特征列表. ' SR_POSITION.post_dfa,CASTER_LINESPEED.post_maxsqt,CASTER_POOL_LEVEL.post_rollingvarmax'
        type: string
      - name: orderfeature
        in: query
        required: true
        description: 用于排序的特征名. ' SR_POSITION.post_dfa'
        type: string

  /kmeanprict:
    post:
      summary: 获得分类标签
      description: 通过KMEAN分类中心值模型，得出分类标签
      operationId: solarcalsupp.post_kmeanprict
      produces:
      - text/plain;
      responses:
        200:
          description: 返回带标签分类。
          schema:
            type: string
          examples:
            "text/plain": '{"5550":{"DFA":0.97951385,"maxpeaksqt":1.67992653,"violmax":5.88352718,"tag":"a"}}'
      parameters:
      - name: array
        in: query
        description: array to calulate.'{"5550":{"DFA":0.97951385,"violmax":5.88352718,"maxpeaksqt":1.67992653}}'
        required: true
        type: string
      - name: centermodel
        in: query
        required: true
        description: 模型. '{"a":{"DFA":0.9685352278,"violmax":5.7472284538,"maxpeaksqt":2.1221870644},"b":{"DFA":1.1660155328,"violmax":14.9333333858,"maxpeaksqt":10.5380230189},"c":{"DFA":1.3348613923,"violmax":31.4501159539,"maxpeaksqt":28.2966994282},"d":{"DFA":1.976394192,"violmax":250.3326660686,"maxpeaksqt":4.9052745478}}'
        type: string
      - name: featurename
        in: query
        required: true
        description: 特征列表. 'SR_POSITION,CASTER_LINESPEED.post_maxsqt,CASTER_POOL_LEVEL.post_rollingvarmax'
        type: string