swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /solarcalhub

paths:
  /mean/{array}:
    post:
      summary: Generate computation restult for mean
      description: 平均值
      operationId: solarcalhub.post_mean
      produces:
        - text/plain;
      responses:
        200:
          description: mean response
          schema:
            type: string
          examples:
            "text/plain": "11.11"
      parameters:
        - name: array
          in: path
          description: array to calulate.
          required: true
          type: string
  /rocsd/{array}:
    post:
      summary: Generate computation restult for roc standard deviation
      description: 变化率标准差
      operationId: solarcalhub.post_rocsd
      produces:
      - text/plain;
      responses:
        200:
          description: rocsd response
          schema:
            type: string
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: string
