swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /solarcalhub

paths:
  /mean/{array}:
    post:
      summary: Generate computation restult for mean
      description: 平均值
      operationId: solarcalhub.post_mean
      produces:
      - text/plain;
      responses:
        200:
          description: mean response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  /rocsd/{array}:
    post:
      summary: Generate computation restult for roc standard deviation
      description: 变化率标准差
      operationId: solarcalhub.post_rocsd
      produces:
      - text/plain;
      responses:
        200:
          description: rocsd response
          schema:
            type: string
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  /dfa/{array}:
    post:
      summary: Generate computation restult for DFA
      description: 去趋势波动分析
      operationId: solarcalhub.post_dfa
      produces:
      - text/plain;
      responses:
        200:
          description: dfa response
          schema:
            type: string
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  /var/{array}:
    post:
      summary: Generate computation restult for variation
      description: 方差计算
      operationId: solarcalhub.post_var
      produces:
      - text/plain;
      responses:
        200:
          description: var response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  /rollingvarmax:
    post:
      summary: Generate computation restult for rolling variation max
      description: 滚动方差最大值计算
      operationId: solarcalhub.post_rollingvarmax
      produces:
      - text/plain;
      responses:
        200:
          description: rolling varmax response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: query
        description: array to calulate.
        required: true
        type: array
        items:
          type: number
      - name: window
        in: query
        description: 窗口大小（个数）
        type: integer
        minimum: 0
        default: 600

  /rollingvarmean:
    post:
      summary: Generate computation restult for rolling variation max
      description: 滚动方差平均计算
      operationId: solarcalhub.post_rollingvarmean
      produces:
      - text/plain;
      responses:
        200:
          description: rolling varmean response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: query
        description: array to calulate.
        required: true
        type: array
        items:
          type: number
      - name: window
        in: query
        description: 窗口大小（个数）
        type: integer
        minimum: 0
        default: 600