swagger: "2.0"

info:
  title: "Demo Calculation Hub"
  version: "1.0"

basePath: /solarcalhub



paths:
  /mean/{array}:
    post:
      summary: 平均值
      description: 平均值
      operationId: solarcalhub.post_mean
      produces:
      - text/plain;
      responses:
        200:
          description: mean response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  /std/{array}:
    post:
      summary: 标准差
      description: 标准差
      operationId: solarcalhub.post_std
      produces:
      - text/plain;
      responses:
        200:
          description: std response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  