swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /solarcalsupp

host: {{host}}

paths:
  /calpoint:
    post:
      summary: 计算得分
      description: 得分落在(-1,1)区间。value 为实际值 ，expect 是期望值， direction 是方向，也可用于权值，负数为越小越好，正数为越大越好.输入可以是序列。
      operationId: solarcalsupp.post_calpoint
      produces:
      - text/plain;
      responses:
        200:
          description: calpoint response
          schema:
            type: number
          examples:
            "text/plain": "0.02123"
      parameters:
      - name: value
        in: query
        description: 实际值
        required: true
        type: array
        items:
          type: number
      - name: expect
        in: query
        description: 期望值
        required: true
        type: array
        items:
          type: number
      - name: direction
        in: query
        description: 权值向量。绝对值和为1。 -0.3, -0.2, -0.2, -0.3
        required: true
        type: array
        items:
          type: number

  /generatelinear:
    post:
      summary: 生成拟合曲线图
      description: 计算最优多项式拟合，生成曲线图
      operationId: solarcalsupp.post_generatelinear
      produces:
      - text/plain;
      responses:
        200:
          description: 生成后返回文件名。
          schema:
            type: string
          examples:
            "text/plain": "6080carlinear.png"
      parameters:
      - name: array
        in: query
        description: array to calulate.
        required: true
        type: array
        items:
          type: number
      - name: batch
        in: query
        description: 批次号
        type: string
      - name: index
        in: query
        description: 指标名称
        type: string
      - name: dpi
        in: query
        description: 图片象素
        type: number

  /generategraph:
    post:
      summary: 生成离散曲线图
      description: 通过数据生成离散折线图
      operationId: solarcalsupp.post_generategraph
      produces:
      - text/plain;
      responses:
        200:
          description: 生成后返回文件名。
          schema:
            type: string
          examples:
            "text/plain": "5550multiplot.png"
      parameters:
      - name: array
        in: query
        description: array to calulate.
        required: true
        type: array
        items:
          type: number
      - name: batch
        in: query
        description: 批次号
        type: string
      - name: index
        in: query
        description: 指标名称
        type: string
      - name: dpi
        in: query
        description: 图片象素
        type: number