swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /solarcalhub

host: {{host}}

paths:
  /mean/{array}:
    post:
      summary: 平均值
      description: 平均值
      operationId: solarcalhub.post_mean
      produces:
      - text/plain;
      responses:
        200:
          description: mean response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  /std/{array}:
    post:
      summary: 标准差
      description: 标准差
      operationId: solarcalhub.post_std
      produces:
      - text/plain;
      responses:
        200:
          description: std response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  /logvolatility/{array}:
    post:
      summary: 对数振荡率
      description: 对数振荡率
      operationId: solarcalhub.post_logVolatility
      produces:
      - text/plain;
      responses:
        200:
          description: logVolatility response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number


  /rocsd/{array}:
    post:
      summary: 变化率标准差
      description: 变化率标准差。变化率在中心取点两边的变化为原理。
      operationId: solarcalhub.post_rocsd
      produces:
      - text/plain;
      responses:
        200:
          description: rocsd response
          schema:
            type: string
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  /skew/{array}:
    post:
      summary: 偏度
      description: 衡量随机分布的不均衡性，偏度 = 0，数值相对均匀的分布在两侧
      operationId: solarcalhub.post_skew
      produces:
      - text/plain;
      responses:
        200:
          description: skew response
          schema:
            type: string
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  /kurtosis/{array}:
    post:
      summary: 峰度
      description: 概率密度在均值处峰值高低的特征
      operationId: solarcalhub.post_kurtosis
      produces:
      - text/plain;
      responses:
        200:
          description: kurtosis response
          schema:
            type: string
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  /dfa/{array}:
    post:
      summary: DFA
      description: 去趋势波动分析。 <0.5, <1 , 1<
      operationId: solarcalhub.post_dfa
      produces:
      - text/plain;
      responses:
        200:
          description: dfa response
          schema:
            type: string
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  /var/{array}:
    post:
      summary: 方差
      description: 方差计算
      operationId: solarcalhub.post_var
      produces:
      - text/plain;
      responses:
        200:
          description: var response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  /maxsqt/{array}:
    post:
      summary: 最大波动率
      description: 最大波动率计算
      operationId: solarcalhub.post_maxsqt
      produces:
      - text/plain;
      responses:
        200:
          description: var response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  /maxpeaksqt/{array}:
    post:
      summary: 极值点最大波动率
      description: 极值点最大波动率计算
      operationId: solarcalhub.post_maxpeaksqt
      produces:
      - text/plain;
      responses:
        200:
          description: max peaksqt response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number


  /meansqt/{array}:
    post:
      summary: 平均波动率
      description: 平均波动率计算
      operationId: solarcalhub.post_meansqt
      produces:
      - text/plain;
      responses:
        200:
          description: var response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: path
        description: array to calulate.
        required: true
        type: array
        items:
          type: number

  /rollingvarmax:
    post:
      summary: 滚动方差最大值
      description: 滚动方差最大值计算，以窗口设置的个数进行顺序滚动
      operationId: solarcalhub.post_rollingvarmax
      produces:
      - text/plain;
      responses:
        200:
          description: rolling varmax response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: query
        description: array to calulate.
        required: true
        type: array
        items:
          type: number
      - name: window
        in: query
        description: 窗口大小（个数）
        type: integer
        minimum: 0
        default: 600

  /rollingvarmean:
    post:
      summary: 滚动方差平均值
      description: 滚动方差平均计算，以窗口设置的个数进行顺序滚动
      operationId: solarcalhub.post_rollingvarmean
      produces:
      - text/plain;
      responses:
        200:
          description: rolling varmean response
          schema:
            type: number
          examples:
            "text/plain": "11.11"
      parameters:
      - name: array
        in: query
        description: array to calulate.
        required: true
        type: array
        items:
          type: number
      - name: window
        in: query
        description: 窗口大小（个数）
        type: integer
        minimum: 0
        default: 600

